name: Run Benchmarks

on:
  # Triggers the workflow every month
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:


jobs:
  run_benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
            path: |
                node_modules
            key: cache-${{ github.run_id }}

      - name: Install Dependencies
        run: npm ci

      - name: Run benchmarks
        run: npm run benchmark 

      - name: Update the benchmark report
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: [skip-ci] update benchmark results"
          branch: master
          file_pattern: report.png
          commit_user_name: "Mark Bench[bot] 💪🏼"
          commit_user_email: markbench[bot]@users.noreply.github.com 
